name: Deploy Content to acmesentinel [7695aa57-fdc6-4f57-97d4-76856d0cd210]

on:
  push:
    branches: [ main ]
    paths:
    - 'BaseRuleSet/**'
    - 'Tenants/AcmeSentinel/**'
    - 'ThirdParty/Acme/**'
    - '!.github/workflows/**'

jobs:
  BaseRulesDeployment:
    runs-on: windows-latest
    env:
      resourceGroupName: 'training_jordan'
      workspaceName: 'acmesentinel'
      workspaceId: '8a587a2c-3d1a-453b-b45e-8022007d20c1'
      directory: '${{ github.workspace }}/BaseRuleSet'
      cloudEnv: 'AzureCloud'
      contentTypes: 'AnalyticsRule'
      branch: 'main'
      sourceControlId: '7695aa57-fdc6-4f57-97d4-76856d0cd210'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
      updateOnlyMode: 'true'
    permissions:
      contents: write
      id-token: write

    steps:
    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_7695aa57fdc64f5797d476856d0cd210 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_7695aa57fdc64f5797d476856d0cd210 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_7695aa57fdc64f5797d476856d0cd210 }}
        enable-AzPSSession: true

    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Get changed files
      id: changed-files
      shell: pwsh
      run: |
        $changedFiles = git diff --name-only HEAD~1 HEAD -- 'BaseRuleSet/*.json'
        $changedFilesString = $changedFiles -join ','
        echo "changed_files=$changedFilesString" >> $env:GITHUB_OUTPUT
        if ([string]::IsNullOrWhiteSpace($changedFilesString)) {
          echo "skip_deployment=true" >> $env:GITHUB_OUTPUT
        } else {
          echo "skip_deployment=false" >> $env:GITHUB_OUTPUT
        }

    - name: Deploy Content to Microsoft Sentinel
      if: steps.changed-files.outputs.skip_deployment == 'false'
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          $env:CHANGED_FILES = "${{ steps.changed-files.outputs.changed_files }}"
          ${{ github.workspace }}//.github/workflows/Acme-SentinelDeployment.ps1


  CustomerRulesDeployment:
    runs-on: windows-latest
    env:
      resourceGroupName: 'training_jordan'
      workspaceName: 'acmesentinel'
      workspaceId: '8a587a2c-3d1a-453b-b45e-8022007d20c1'
      directory: '${{ github.workspace }}/Tenants/AcmeSentinel'
      cloudEnv: 'AzureCloud'
      contentTypes: 'AnalyticsRule'
      branch: 'main'
      sourceControlId: '7695aa57-fdc6-4f57-97d4-76856d0cd210'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write

    steps:
    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_7695aa57fdc64f5797d476856d0cd210 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_7695aa57fdc64f5797d476856d0cd210 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_7695aa57fdc64f5797d476856d0cd210 }}
        enable-AzPSSession: true

    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Get changed files
      id: changed-files
      shell: pwsh
      run: |
        $changedFiles = git diff --name-only HEAD~1 HEAD -- 'Tenants/AcmeSentinel/*.json'
        $changedFilesString = $changedFiles -join ','
        echo "changed_files=$changedFilesString" >> $env:GITHUB_OUTPUT
        if ([string]::IsNullOrWhiteSpace($changedFilesString)) {
          echo "skip_deployment=true" >> $env:GITHUB_OUTPUT
        } else {
          echo "skip_deployment=false" >> $env:GITHUB_OUTPUT
        }

    - name: Deploy Content to Microsoft Sentinel
      if: steps.changed-files.outputs.skip_deployment == 'false'
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          $env:CHANGED_FILES = "${{ steps.changed-files.outputs.changed_files }}"
          ${{ github.workspace }}//.github/workflows/Acme-SentinelDeployment.ps1


  ThirdPartyRulesDeployment:
    runs-on: windows-latest
    env:
      resourceGroupName: 'training_jordan'
      workspaceName: 'acmesentinel'
      workspaceId: '8a587a2c-3d1a-453b-b45e-8022007d20c1'
      directory: '${{ github.workspace }}/ThirdParty/Acme'
      cloudEnv: 'AzureCloud'
      contentTypes: 'AnalyticsRule'
      branch: 'main'
      sourceControlId: '7695aa57-fdc6-4f57-97d4-76856d0cd210'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write

    steps:
    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_7695aa57fdc64f5797d476856d0cd210 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_7695aa57fdc64f5797d476856d0cd210 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_7695aa57fdc64f5797d476856d0cd210 }}
        enable-AzPSSession: true

    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Get changed files
      id: changed-files
      shell: pwsh
      run: |
        $changedFiles = git diff --name-only HEAD~1 HEAD -- 'ThirdParty/Acme/*.json'
        $changedFilesString = $changedFiles -join ','
        echo "changed_files=$changedFilesString" >> $env:GITHUB_OUTPUT
        if ([string]::IsNullOrWhiteSpace($changedFilesString)) {
          echo "skip_deployment=true" >> $env:GITHUB_OUTPUT
        } else {
          echo "skip_deployment=false" >> $env:GITHUB_OUTPUT
        }

    - name: Deploy Content to Microsoft Sentinel
      if: steps.changed-files.outputs.skip_deployment == 'false'
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          $env:CHANGED_FILES = "${{ steps.changed-files.outputs.changed_files }}"
          ${{ github.workspace }}//.github/workflows/Acme-SentinelDeployment.ps1
