name: Deploy Content to acmesentinel [7d51fe0d-6917-4bfc-9f7c-c65e230510f0]

on:
  push:
    branches: [ main ]
    paths:
      - 'MasterWizard/**'
      - 'Base Rule Set/**'
      - '!.github/workflows/**'
      - '.github/workflows/sentinel-deploy-7d51fe0d-6917-4bfc-9f7c-c65e230510f0.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'training_jordan'
      workspaceName: 'acmesentinel'
      workspaceId: '8a587a2c-3d1a-453b-b45e-8022007d20c1'
      rootDirectory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'AnalyticsRule'
      branch: 'main'
      sourceControlId: '7d51fe0d-6917-4bfc-9f7c-c65e230510f0'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
      directories: 'MasterWizard,Base Rule Set'
    permissions:
      contents: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_7d51fe0d69174bfc9f7cc65e230510f0 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_7d51fe0d69174bfc9f7cc65e230510f0 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_7d51fe0d69174bfc9f7cc65e230510f0 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          # Split folders into an array
          $Directories = $Env:directories -split ","
          
          # Loop through each folder and deploy
          foreach ($folder in $Directories) {
              $env:directory = Join-Path $Env:rootDirectory $folder
              Write-Host "Deploying folder: $env:directory"
              pwsh "${{ github.workspace }}/.github/workflows/azure-sentinel-deploy-7d51fe0d-6917-4bfc-9f7c-c65e230510f0.ps1" -Path "$env:directory"
          }
