name: Deploy Content to templaw [85b18938-fe0f-4011-b4df-32df159b9cfc]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-85b18938-fe0f-4011-b4df-32df159b9cfc.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ main ]
    paths:
    - 'BaseRuleSet/**'
    - 'TempLaw/**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow

jobs:
  BaseRulesDeployment:
    runs-on: windows-latest
    env:
      resourceGroupName: 'temptest'
      workspaceName: 'templaw'
      workspaceId: '98739ee3-5b09-4317-bf39-65dc869e4db3'
      directory: '${{ github.workspace }}/BaseRuleSet'
      cloudEnv: 'AzureCloud'
      contentTypes: 'AnalyticsRule'
      branch: 'main'
      sourceControlId: '85b18938-fe0f-4011-b4df-32df159b9cfc'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_85b18938fe0f4011b4df32df159b9cfc }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_85b18938fe0f4011b4df32df159b9cfc }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_85b18938fe0f4011b4df32df159b9cfc }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_85b18938fe0f4011b4df32df159b9cfc }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_85b18938fe0f4011b4df32df159b9cfc }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_85b18938fe0f4011b4df32df159b9cfc }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_85b18938fe0f4011b4df32df159b9cfc }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_85b18938fe0f4011b4df32df159b9cfc }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_85b18938fe0f4011b4df32df159b9cfc }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |

          ${{ github.workspace }}//.github/workflows/Acme-SentinelDeployment.ps1


